# Utiliser l'image openjdk:17 comme base
FROM openjdk:17

# Exposer le port 8080 pour l'application
EXPOSE 8761

# Ajouter le fichier JAR construit dans le conteneur et le renommer en Produits.jar
ADD target/discovery-server-0.0.1-SNAPSHOT.jar discovery-server.jar

# Définir l'entrée de l'application Java
ENTRYPOINT ["java", "-jar", "discovery-server.jar"]
